name: 29920 - Deploy

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  REPONAME: ${{ secrets.REPO_NAME }}

on:
  workflow_run:
    workflows: ["29920 - Testiranje"]
    types:
      - completed

jobs:
  preveri_artefakt:
    name: Preveri rezultat testov
    runs-on: self-hosted
    if: github.event.workflow_run.conclusion == 'success'

    outputs:
      build_date: ${{ steps.datum.outputs.date }}
    steps:
      - name: Checkout repozitorija
        uses: actions/checkout@v4

      - name: Prenesi napaka.txt
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: 29920_test.yml
          workflow_conclusion: success
          branch: main
          name: napaka-c99
          path: ./artefakti

      - name: Preveri napaka.txt
        run: |
          if [ ! -f ./artefakti/napaka.txt ]; then
            exit 1
          fi

          value=$(cat ./artefakti/napaka.txt)
          echo "Vsebina napaka.txt: $value"

          if [ -s ./artefakti/napaka.txt ]; then
            exit 1
          fi

      - name: Trenutni cas
        id: datum
        run: |
          echo "date=$(date +'%Y-%m-%d--%H-%M-%S')" >> "$GITHUB_OUTPUT"

      - name: Potisni na docker hub z akcijo
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          registry: docker.io
          dockerfile: Dockerfile
          tags: ${{ steps.datum.outputs.date }}
          image: ${{ env.DOCKER_USERNAME }}/${{ env.REPONAME }}

  release:
    needs: preveri_artefakt
    runs-on: self-hosted
    steps:
      - name: Izpis datuma objave iz prvega joba
        run: echo ${{ needs.preveri_artefakt.outputs.build_date }}
